### PR TITLE
Accounts main fix

### LINKED ISSUE #173: User sees events for all accounts in the overview, rather than just the current account

### PR DESCRIPTION
**Pull request by n13**
- Main screen shows only active tx
- Transactions history screen de-duplicated.

Fixes #173

### CODE REVIEW

File: mobile-app/lib/features/main/screens/wallet_main.dart [hunk 1]
```diff
@@ -242,7 +243,7 @@ class _WalletMainState extends ConsumerState<WalletMain> {
   Widget build(BuildContext context) {
     final activeAccountAsync = ref.watch(activeAccountProvider);
     final balanceAsync = ref.watch(balanceProvider);
-    final allTransactionsAsync = ref.watch(allTransactionsProvider);
+    final allTransactionsAsync = ref.watch(activeAccountTransactionsProvider);
```
Comment (dewabisma) [inline mobile-app/lib/features/main/screens/wallet_main.dart:246]: The variable name can be misleading for this one

**Review by dewabisma — APPROVED** [review]
Looks good 👍🏽
